### ISSUE TITLE
continue reddit discussion

### ISSUE THREAD

**Issue by Code-Slave** [Dannyman3819/Automatic-Youtube-Downloader#1]
To continue thoughts.

what i saw in code so far is you have duplicated some code thats already in youtube-dl
(track downloads,read from a text files the channels)

what i was looking to do is add a frontend to managing the data youtube-dl ingests as my work flow is to add a link to a channel to the categories text file. then i have seperate bash scripts for each category that rads that categories text file. grabs latest vids (or all if just starting) and saves downloaded into its own categories text file. the files are saved in catgory/channelname. in a format acceptable for the the plex plugins. It works but I think it could be much more refined by either managing the categories and texts or more of a front end as you have done. Your system is very good and poped up on radar on reddit.

**Comment by PizzaWaffles** [comment]
I honestly didn't even know Youtube-dl had that functionality. I will take a look at it when I get home or over the weekend.
Also i think I could help you out. I think it might be more seamless if you had one file to organize everything for example one line would be "[channel ID] [category]" then I could sort all those videos into that categories directory.

**Comment by Code-Slave** [comment]
Yea. There is a lot to youtube-dl. You can also import it so you dont have to shell out to it. 

Ill post my config in a few to show what i do. The more i think about it the more i like the idea of managing the categories and channels in a wrapper. 

I even think a light flask frontend might be nice

**Comment by PizzaWaffles** [comment]
Well I definitely don't have time to code a web frontend between school and work. I wanted to implement a small gui which might make things easier

**Comment by Code-Slave** [comment]
Yea. Me either really just thinking out loud
