### ISSUE TITLE
Problem with feed sending down file with directory seperator in the name

### ISSUE THREAD

**Issue by bchmura** [Dannyman3819/Automatic-Youtube-Downloader#13]
Had a feed that mentioned AC/DC in the subscription.  I will put a code fix in for this right after the logging goes in,

**Comment by PizzaWaffles** [comment]
I may have fixed this issue when I worked on the uft-8 fixes. Please retest this issue.

**Comment by bchmura** [comment]
It looks like the offending character has been removed, seems better
