### ISSUE TITLE
Title of folder for ASS

### ISSUE THREAD

**Issue by zelik888** [Dannyman3819/Automatic-Youtube-Downloader#16]
I have just updated to latest version but titles are still incorrect for the channel folder, it still only shows the name and not the required channel id ? I have to manually rename youtube channel inside plex.

**Comment by bchmura** [comment]
What requires the channel ID to be in the folder tile?  I'm looking through the spec's for the scanner and not finding anything.

**Comment by PizzaWaffles** [comment]
Newest update of setup.py takes care of this you can run the first time setup again or just change some lines in your "data/config" file.
Change the DESTINATION_FORMAT and FILE_FORMAT variables to
`DESTINATION_FORMAT=%NAME [Youtube-$CHANNEL_ID]`
`FILE_FORMAT=%TITLE - [%VIDEO_ID]`

**Comment by zelik888** [comment]
thanks for the update, ran through new install and also reran setup, indicated ASS but still not naming folders with ID  should i just use extended scanner instead?

**Comment by zelik888** [comment]
It’s some problem with YouTube agent I think, it doesn’t like folder names with just the name of channel. Let me look into this a little more. I installed this last week but I’ll update the YouTube agent again later today
