### ISSUE TITLE
Multiple files for single video

### ISSUE THREAD

**Issue by mtehonica** [Dannyman3819/Automatic-Youtube-Downloader#18]
I'm seeing this warning when I run the script and it's outputting 2 files for each YouTube video (.f248 and .f251).

`WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.`

Ubuntu 16.04
PMS 1.13.7
Python 3.5.2

**Comment by PizzaWaffles** [comment]
Please run `sudo apt-get install ffmpeg`

**Comment by mtehonica** [comment]
Thanks, that seems to have fixed it.  We need to make this into a Docker container :D

**Comment by Glenta** [comment]
I get the same for Windows 10, how do I fix this?
