### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by mtehonica** [Dannyman3819/Automatic-Youtube-Downloader#19]
I'm interested in creating a Docker container for this.  Is it possible to add some type of flag so we can separate all the static "app" files from all the "config" stuff?  Then we can store the config stuff to a persistent volume.  I think the best way would be to add a flag for setup.py for `--config` and specify where you want the config stuff to be stored.

**Comment by PizzaWaffles** [comment]
I don't have much experience with docker so that would be cool. The flag for setup.py would be easy to implement, let me code it real quick. Is that all you need changed to setup a docker container?

**Comment by mtehonica** [comment]
I think that is the biggest hurdle right now.  I think we'll also need a different option for the setup.py because we'll want to generate the config but not run all the dependency checks and all that.  We'll guarantee the dependancies are correct in the container.  We'll also only need to know what interval the user wants to run the script at because that will be the only option for it in the container.

**Comment by PizzaWaffles** [comment]
Updated setup.py to add this functionality.

**Comment by dan-the-man-nz** [comment]
Did you publish this docker image? Cheers
