### ISSUE TITLE
Format best does not download 4k

### ISSUE THREAD

**Issue by Just-Insane** [Dannyman3819/Automatic-Youtube-Downloader#22]
When manually setting the format to best (see below), youtube-dl only downloads the video in 1080p, even if there is a 4k version available. It downloads the video as VP9 and the audio as OPUS, which to my understanding is what is needed for 4k video. The file extension is .webm, however plex only sees the files as 1080p.

This is with ffmpeg merging the two files together.

config:
`VIDEO_FORMAT=best`

**Comment by omega8fattyacid** [comment]
Have 4k downloads actually been added yet? I'm having the same issue.

**Comment by PizzaWaffles** [comment]
I confirmed the issue, please edit your data/config file change the VIDEO_FORMAT value to '313+251/best' this will download 4k or best if 4k is not available.
