### ISSUE TITLE
Tautulli Users

### ISSUE THREAD

**Issue by CarnalMischief** [Dannyman3819/Automatic-Youtube-Downloader#24]
Hi,
How do you go about installing this if you already have Tautulli installed and working fine (as it only works on Python 2.7.??) whereas your instructions for YTD seem to imply you need Python 3.5.

I'm getting error messages during the install (setup.py - select option 1) on a Windows 10 PC, but they're flashing up so fast I can't see what the error is and the log file has no real info in it.

First run / setup:-

12/02/2018 12:56:31 PM Program setup.py started
12/02/2018 12:56:31 PM Data directory not found, creating...
12/02/2018 12:56:31 PM Download directory not found, creating...
12/02/2018 12:56:31 PM log.txt not found, creating...
12/02/2018 12:56:37 PM At main menu, user selected option 1

When I chose option 1 a second time I got the following:-

12/02/2018 12:56:31 PM Program setup.py started
12/02/2018 12:56:31 PM Data directory not found, creating...
12/02/2018 12:56:31 PM Download directory not found, creating...
12/02/2018 12:56:31 PM log.txt not found, creating...
12/02/2018 12:56:37 PM At main menu, user selected option 1
12/02/2018 01:00:07 PM Program setup.py started
12/02/2018 01:02:18 PM Program setup.py started
12/02/2018 01:02:24 PM At main menu, user selected option 1
12/02/2018 01:02:24 PM lzma module is not available
12/02/2018 01:02:24 PM Registered VCS backend: git
12/02/2018 01:02:24 PM Registered VCS backend: hg
12/02/2018 01:02:24 PM Registered VCS backend: svn
12/02/2018 01:02:24 PM Registered VCS backend: bzr
12/02/2018 01:02:24 PM For variant 'global', will try loading 'C:\ProgramData\pip\pip.ini'
12/02/2018 01:02:24 PM For variant 'user', will try loading 'C:\Users\SysAdmin\pip\pip.ini'
12/02/2018 01:02:24 PM For variant 'user', will try loading 'C:\Users\SysAdmin\AppData\Roaming\pip\pip.ini'
12/02/2018 01:02:24 PM For variant 'global', will try loading 'C:\ProgramData\pip\pip.ini'
12/02/2018 01:02:24 PM For variant 'user', will try loading 'C:\Users\SysAdmin\pip\pip.ini'
12/02/2018 01:02:24 PM For variant 'user', will try loading 'C:\Users\SysAdmin\AppData\Roaming\pip\pip.ini'

Also I think your install removed my already installed PIP and didn't put it back (i'm still looking into this)

If I get any further I'll come back to you.

Thanks

**Comment by PizzaWaffles** [comment]
Newest version should fix these python version issues. See [this](https://github.com/Dannyman3819/Automatic-Youtube-Downloader#to-version-10) for updating to version 1.0
