### ISSUE TITLE
How to check if running?

### ISSUE THREAD

**Issue by clemone210** [Dannyman3819/Automatic-Youtube-Downloader#26]
Hi,
I just setp everything up and set that it will run at startup and every x minutes.
How do I check if its running?

Can I set up a manual download? So like force download the latest videos?

Thanks

**Comment by clemone210** [comment]
It gets me this error when trying to run


![unbenannt](https://user-images.githubusercontent.com/43761260/50852593-4b34bd80-1380-11e9-8cb8-321bd04db9a2.JPG)

**Comment by clemone210** [comment]
ok got it working for now. How do setup automatically put a Channel Poster for the channel?

**Comment by clemone210** [comment]
How to fix this?
Running 2.7.15

```
Traceback (most recent call last):
  File "main.py", line 515, in <module>
    loggingFile = open('main.log', 'a', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by clemone210** [comment]
added:

```
import sys
if sys.version_info[0] > 2:
    # py3k
    pass
else:
    # py2
    import codecs
    import warnings
    def open(file, mode='r', buffering=-1, encoding=None,
             errors=None, newline=None, closefd=True, opener=None):
        if newline is not None:
            warnings.warn('newline is not supported in py2')
        if not closefd:
            warnings.warn('closefd is not supported in py2')
        if opener is not None:
            warnings.warn('opener is not supported in py2')
        return codecs.open(filename=file, mode=mode, encoding=encoding,
                    errors=errors, buffering=buffering)
					

import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

to get my problem fixed with Python 2.7.15

**Comment by clemone210** [comment]
how to skip videos which are not available in my country?

**Comment by PizzaWaffles** [comment]
Hello sorry for the late reply I looked into it and there is no way to check if a video is region block. However you could ignore the errors to skip the video. Add this after line 426
`'ignoreerrors': 'true',`
