### ISSUE TITLE
Cannot run main.py

### ISSUE THREAD

**Issue by Rexios80** [Dannyman3819/Automatic-Youtube-Downloader#27]
I cannot run main.py. I tried to debug it myself, but I don't have enough python experience to know what's going on. Here is the console output:

python3.5 main.py
--Using data/config
Traceback (most recent call last):
  File "main.py", line 574, in <module>
    main()
  File "main.py", line 357, in main
    get_icons(xmltitle, channelIDlist)
  File "main.py", line 129, in get_icons
    if not (chid[0] in downloaded):
IndexError: list index out of range

**Comment by dblevin1** [comment]
Make sure you run the setup.py first and setup the channels you want to download. That error usually means the youtubeData.xml file in data/ is empty.

**Comment by PizzaWaffles** [comment]
Make sure you run the setup.py first and setup the channels you want to download. That error usually means the youtubeData.xml file in data/ is empty.

**Comment by Rexios80** [comment]
I figured it was something like that, but I already ran the setup and my youtubeData.xml isn’t empty. Perhaps they changed the format of the exported file?

**Comment by Rexios80** [comment]
Okay somehow my youtubeData.xml was empty even though I had already replaced it and ran the setup. Sorry for the wasted time.

**Comment by Rexios80** [comment]
Actually it seems like the setup is destroying the youtubeData.xml. I'm not sure if it's just my environment or not though.

**Comment by ksaechao** [comment]
Same issue:

```
C:\Automatic-Youtube-Downloader>python main.py
--Using data/config
Traceback (most recent call last):
  File "main.py", line 574, in <module>
    main()
  File "main.py", line 357, in main
    get_icons(xmltitle, channelIDlist)
  File "main.py", line 129, in get_icons
    if not (chid[0] in downloaded):
IndexError: list index out of range

```

**Comment by dblevin1** [comment]
Ok took me awhile to reproduce but I tracked down the bug and updated the repo. Please re-download setup.py and main.py and copy them into your current directory then you'll need to re-run setup.py.

**Comment by PizzaWaffles** [comment]
Ok took me awhile to reproduce but I tracked down the bug and updated the repo. Please re-download setup.py and main.py and copy them into your current directory then you'll need to re-run setup.py.

**Comment by Rexios80** [comment]
I am now getting this error. My youtubeData.xml isn't empty.

  File "main.py", line 129
    print("Error youtubeData.xml file empty please run setup.py to fix")
                                                                       ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Rexios80** [comment]
Somehow that print line uses tabs instead of spaces for indentation. I fixed it by changing the 2 tabs to 8 spaces.

**Comment by Rexios80** [comment]
One question I have is do I have to run setup.py? Or can I simply provide a config file and youtubeData.xml.

**Comment by PizzaWaffles** [comment]
#28
