### ISSUE TITLE
Cross-Platform (Linux) issue with posters not moving

### ISSUE THREAD

**Issue by Rexios80** [Dannyman3819/Automatic-Youtube-Downloader#28]
I finally got my videos to download, but the posters aren't downloading correctly. They end up in my downloads folder, but don't get moved to their channel folders.

01/24/2019 02:21:56 PM Program main.py started
01/24/2019 02:21:56 PM Loading config file from data/config
01/24/2019 02:21:56 PM Checking line API_KEY=[REDACTED] as API_KEY = [REDACTED]
01/24/2019 02:21:56 PM Setting API_KEY to [REDACTED]
01/24/2019 02:21:56 PM Checking line SCHEDULING_MODE=DELAY as SCHEDULING_MODE = DELAY
01/24/2019 02:21:56 PM Setting SCHEDULING_MODE to DELAY
01/24/2019 02:21:56 PM Checking line SCHEDULING_MODE_VALUE=15 as SCHEDULING_MODE_VALUE = 15
01/24/2019 02:21:56 PM Setting SCHEDULING_MODE_VALUE to 15
01/24/2019 02:21:56 PM Checking line NUM_VIDEOS=3 as NUM_VIDEOS = 3
01/24/2019 02:21:56 PM Setting NUM_VIDEOS to 3
01/24/2019 02:21:56 PM Checking line DESTINATION_FOLDER=/home/user/files/Plex/YouTube/ as DESTINATION_FOLDER = /home/user/files/Plex/YouTube/
01/24/2019 02:21:56 PM Setting DESTINATION_FOLDER to /home/user/files/Plex/YouTube/
01/24/2019 02:21:56 PM Checking line DESTINATION_FORMAT=%NAME as DESTINATION_FORMAT = %NAME
01/24/2019 02:21:56 PM Setting DESTINATION_FORMAT to %NAME
01/24/2019 02:21:56 PM Checking line FILE_FORMAT=%NAME - %UPLOAD_DATE - %TITLE as FILE_FORMAT = %NAME - %UPLOAD_DATE - %TITLE
01/24/2019 02:21:56 PM Setting FILE_FORMAT to %NAME - %UPLOAD_DATE - %TITLE
01/24/2019 02:21:56 PM get_icons called
01/24/2019 02:21:56 PM Downloading new icon for poster:  | UCLE-OsLBsCTTQIs_JfBKnkw
01/24/2019 02:21:56 PM icon url is [not recorded due to API key being included]
01/24/2019 02:21:56 PM list index out of range
01/24/2019 02:21:56 PM Traceback (most recent call last):
  File "main.py", line 171, in get_icons
    icon_url = data['items'][0]['snippet']['thumbnails']['high']['url']
IndexError: list index out of range

**Comment by PizzaWaffles** [comment]
The channel you are trying to download does not exist 
https://www.youtube.com/channel/UCLE-OsLBsCTTQIs_JfBKnkw

**Comment by Rexios80** [comment]
Weird that channel id isn't in my youtubeData.xml

**Comment by Rexios80** [comment]
It seems like it is creating files in the format of "{channel_name}\poster.jpg" instead of placing "poster.jpg" into the channel's download folder.

01/29/2019 11:16:59 PM icon url is [not recorded due to API key being included]
01/29/2019 11:16:59 PM destination directory was not found for Download/videogamedunkey
01/29/2019 11:16:59 PM Downloading new icon for poster: videogamedunkey | UCsvn_Po0SmunchJYOWpOxMg

This generates a file named "videogamedunkey\poster.jpg" and does not place it in the channel folder.

**Comment by Rexios80** [comment]
So it turns out the script is using the Windows directory structure with "\\" whereas linux uses "/". I changed it in main.py and the script is now putting the posters into the channel folders, but Plex still isn't picking them up. If you have any ideas how to fix this I would greatly appreciate it.

**Comment by Rexios80** [comment]
I moved "Local Media Assets" to the top in the Extended Personal Media Shows agent and it now works flawlessly.

**Comment by dblevin1** [comment]
Perfect glad you got it working. Could you make a pull request with the changes you made?

**Comment by PizzaWaffles** [comment]
Perfect glad you got it working. Anyway you could do a pull request with the changes you made?

**Comment by Rexios80** [comment]
I can PR the tabs to spaces, but you'll need to do more work than I did for the directory structure thing to work cross platform. Yours only works on Windows, mine should only work on Unix/Linux.

**Comment by PizzaWaffles** [comment]
I see OK no worries then let me know if you run into anymore issues.

**Comment by Rexios80** [comment]
Are you going to work on the cross platform thing? If not I might be able to find some time to do it myself. It shouldn't be too hard, I just didn't want to have to deal with QA.

**Comment by PizzaWaffles** [comment]
No thats ok I have a lot of changes I need to test on different platforms so Ill just test it at the same time.

**Comment by Rexios80** [comment]
I was just confused because you closed the issue but the problem wasn't fixed

**Comment by PizzaWaffles** [comment]
Newest version should fix these issues. See [this](https://github.com/Dannyman3819/Automatic-Youtube-Downloader#to-version-10) for updating to version 1.0
