### ISSUE TITLE
Unexpected crash when selecting all in setup.py

### ISSUE THREAD

**Issue by bramnet** [Dannyman3819/Automatic-Youtube-Downloader#36]
So, I'm not sure what caused this, but when I use setup.py to select all of the channels I'm subscribed to

PS E:\GitHub\Automatic-Youtube-Downloader> python setup.py
--Outputting data to:data/youtubeData.xml
--Config file:data/config

        1. First Time Install
        2. Channel Selection
        3. Install Dependencies
        4. Add Single Channel Manually
        5. Edit Configurations
        6. Exit/Quit

What would you like to do?
2
Parsing Youtube data...

Would you like to select which channels you want to include, or do you want to include all of them?
If you include all channels you can remove them manually by editing data/youtubeData.xml and deleting the entire line of the channel you do not want (Choose this option if you have a lot of subscriptions)
Enter 'all' to keep all subscriptions or 'select' to select which channels (or 'a' or 's'):
a
Including all channels

Traceback (most recent call last):
  File "setup.py", line 688, in <module>
    main(configFile, dataFile, skipDep)
  File "setup.py", line 609, in main
    channel_selection(dataFile)
  File "setup.py", line 207, in channel_selection
    titleList[count] = channel.title
TypeError: 'NoneType' object does not support item assignment

it crashes.
Here's an output of the log file for additional debugging.

03/08/2019 07:38:40 PM Program setup.py started
03/08/2019 07:38:40 PM Data directory not found, creating...
03/08/2019 07:38:40 PM Download directory not found, creating...
03/08/2019 07:38:40 PM log.txt not found, creating...
03/08/2019 07:38:45 PM At main menu, user selected option 1
03/09/2019 11:31:10 PM Program setup.py started
03/09/2019 11:32:08 PM User exited program
03/13/2019 02:46:34 AM Program setup.py started
03/13/2019 02:48:28 AM User exited program
03/30/2019 10:29:06 PM Program setup.py started
03/30/2019 10:29:25 PM Channel_selection started
03/30/2019 10:29:42 PM User selected a for all or single channel selection
03/30/2019 10:29:42 PM Opening data/youtubeData.xml for writing
03/30/2019 10:29:57 PM Program setup.py started
03/30/2019 10:30:02 PM Channel_selection started
03/30/2019 10:30:04 PM User selected a for all or single channel selection
03/30/2019 10:30:04 PM Opening data/youtubeData.xml for writing
03/30/2019 10:33:13 PM Program setup.py started
03/30/2019 10:33:19 PM Channel_selection started
03/30/2019 10:33:22 PM User selected a for all or single channel selection
03/30/2019 10:33:22 PM Opening data/youtubeData.xml for writing
03/30/2019 10:39:31 PM Program setup.py started
03/30/2019 10:39:34 PM Channel_selection started
03/30/2019 10:39:36 PM User selected a for all or single channel selection
03/30/2019 10:39:36 PM Opening data/youtubeData.xml for writing

P.S. due to the xml file being opened for writing, the entire file is now empty and unusable by main.py

**Comment by PizzaWaffles** [comment]
There was an issue with the channel selection option I made some changes and posted an update.

**Comment by bramnet** [comment]
I *think* that might have solved the issue, but now I'm having a new problem. It appears to be asking for my channel ID, but each time I input it, the log returns a 403. I've noticed that this is to scrape the channel for the subscriptions, but is there a way to just let it use the .xml file like before?

**Comment by PizzaWaffles** [comment]
I could yes but my thinking was if you subscribe to a new channel on Youtube this would automatically show an updated list of channels that could be selected. 
PS if the program hasn't saved it yet you can put your channel id in the config file just add a new line with this variable 
```
MY_CHANNEL_ID=[put your channel id here without quotes or brackets]
```

**Comment by PizzaWaffles** [comment]
Ill see if i can add another option to just use the subscription xml file

**Comment by bramnet** [comment]
Thanks. Long story short, the main youtube account I use is a brand account, which I think complicates things on their side (since the api was created under my account, but the brand account doesn't count as "my" account even though I own it.) I tried to fix it myself, but best I could get was an authorization token.
