### ISSUE TITLE
Exception when attempting first run setup

### ISSUE THREAD

**Issue by wackedchewbacca** [Dannyman3819/Automatic-Youtube-Downloader#38]
Getting an error when trying to install. 

> Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Automatic-Youtube-Downloader-master\setup.py", line 732, in <module>
    main(configFile, dataFile, skipDep)
  File "C:\Users\Admin\Desktop\Automatic-Youtube-Downloader-master\setup.py", line 631, in main
    channel_selection(dataFile, "", titleList, idList)
  File "C:\Users\Admin\Desktop\Automatic-Youtube-Downloader-master\setup.py", line 186, in channel_selection
    import listparser as lp
ImportError: No module named 'listparser'
>>> 

> 

I'm running windows 10, no AV and everything is updated. I'm not getting a log file outputted nor a config file. 

Thanks

**Comment by PizzaWaffles** [comment]
Try and run this
```pip install -r requirements.txt```

**Comment by wackedchewbacca** [comment]
I'm just getting a syntax error with that.

**Comment by wackedchewbacca** [comment]
> C:\Users\Admin\Desktop\Automatic-Youtube-Downloader-master>python
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install -r requirements.txt
  File "<stdin>", line 1
    pip install -r requirements.txt
              ^
SyntaxError: invalid syntax
>>>

>

**Comment by wackedchewbacca** [comment]
Ok, apologies. I think I now have it sorted. For anyone else searching and having similar issues (Noob issues admittedly) 
Make sure python is added to your PATH, including an extra line for python/scripts, to allow the pip command to work. 
Also bear in mind that the pip command only works from CMD, as python is an interpreter, whereas PIP is an installer for extra python bits.
This allowed me to install the extras from the 'requirements.txt' file and get the install completed. 
Thanks Dannyman! Much appreciated.
