### ISSUE TITLE
Audio not Merging with Video

### ISSUE THREAD

**Issue by PizzaWaffles** [Dannyman3819/Automatic-Youtube-Downloader#4]
I believe its due to ffmpeg not being installed on some machines. Working on a fix now.

**Comment by PizzaWaffles** [comment]
Hopefully fixed with last commit.

**Comment by bchmura** [comment]
Maybe because of all the diff systems this can run on and the several ways to get ffmpeg installed just perform a check during setup (like a pre-flight check) and report back?  Would not make it super easy for the user, but a lot better.
