### ISSUE TITLE
crash on setup

### ISSUE THREAD

**Issue by brgipple** [Dannyman3819/Automatic-Youtube-Downloader#41]
I am new to programming, Github, the youtube downloader and plex, so excuse my ignorance with this issue but when I attempt to run set up, It runs successfully through the API step and it says that it was a success. When I enter my youtube information and hit enter, some red text appears in the window and then it crashes. It is not open long enough for me to read it and I'm not sure where to look for more information about what happened. I'm using Windows 10 and I know that I can use Youtube-dl.exe to manually download.

**Comment by brgipple** [comment]
I did find the log file and this was the output

05/10/2019 07:21:00 PM Program setup.py started
05/10/2019 07:21:01 PM At main menu, user selected option 1
05/10/2019 07:28:35 PM get_API_key function called
05/10/2019 07:28:35 PM Gathering API key info
05/10/2019 07:28:55 PM Google API Key returned 200 (success)
05/10/2019 07:29:13 PM ERROR: My Channel Key incorrect
05/10/2019 07:29:13 PM ERRORHTTP Error 403: Forbidden
05/10/2019 07:29:13 PM Traceback (most recent call last):
  File "Z:\Automatic-Youtube-Downloader-master\Automatic-Youtube-Downloader-master\setup.py", line 562, in get_sub_list
    '')
  File "C:\Users\brgip\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\brgip\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\brgip\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\brgip\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\brgip\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\brgip\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by PizzaWaffles** [comment]
Please update your setup.py file download the latest version [here](https://raw.githubusercontent.com/Dannyman3819/Automatic-Youtube-Downloader/master/setup.py) just replace it in your directory. 
Please let me know if this version works for you.

**Comment by brgipple** [comment]
still the same results

**Comment by PizzaWaffles** [comment]
OK so setup.py first uses your API key to try and get your subscriptions but Ive seen some weird access issues doing that.
With the updated version of the setup.py when it asks for your channel ID just leave it blank and press enter, this will prompt you toward an alternative way of getting your subscriptions.

**Comment by brgipple** [comment]
I think this issue is fixed, now. I ran setup and downloaded the exported subscription manager xml, I ran main.py, which the log for that says that it is running but now I cannot access options/config.

**Comment by PizzaWaffles** [comment]
Great. Yes you have to rerun setup.py to change settings or edit the config file located in the data/ directory.
