### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by r4czo** [Dannyman3819/Automatic-Youtube-Downloader#42]
Icant get this to work it finds the file but when i open setup.py it just says that config file does not exist. Here is the error i get when i do the setup 

Setting up Youtube configs
Please goto https://www.youtube.com/subscription_manager
On the bottom of the page click 'Export Subscriptions'
Put that file in the data directory so it looks like data/subscription_manager.xml
Click enter to continue.....

File Found

Traceback (most recent call last):
  File "setup.py", line 762, in <module>
    main(configFile, dataFile, skipDep)
  File "setup.py", line 655, in main
    channel_selection(dataFile, "data/subscription_manager.xml")
  File "setup.py", line 194, in channel_selection
    import listparser as lp
ImportError: No module named 'listparser'
PS C:\Users\Oscar\Desktop\Automatic-Youtube-Downloader-master>

Setup LOG:
07/02/2019 05:35:22 PM Program setup.py started
07/02/2019 05:35:25 PM At main menu, user selected option 1
07/02/2019 05:35:25 PM install_dependencies function called
07/02/2019 05:36:00 PM get_API_key function called
07/02/2019 05:36:00 PM Gathering API key info
07/02/2019 05:36:27 PM Google API Key returned 200 (success)
07/02/2019 05:36:27 PM get_sub_list function called
07/02/2019 05:36:31 PM format_youtube_data function called
07/02/2019 05:36:36 PM subscription_manager.xml was found
07/02/2019 05:36:36 PM channel_selection function called

**Comment by r4czo** [comment]
I ran this command and now i got past that problem, you should add this in the install guide!

pip install -r requirements.txt

**Comment by PizzaWaffles** [comment]
Thank you, added to the README.
https://github.com/PizzaWaffles/Automatic-Youtube-Downloader/commit/37287ba7b0d5bea3f07df850b79017212e74c577
