### ISSUE TITLE
Get API Key for YouTube -> Step 9 I cannot find where can I validate the API key

### ISSUE THREAD

**Issue by chloe0730000** [Dannyman3819/Automatic-Youtube-Downloader#48]
Hi, I have followed the instructions and seems like I cannot figure out where can I go to the step 9. Could you provide me the link to there thanks!
https://www.slickremix.com/docs/get-api-key-for-youtube/

**Comment by PizzaWaffles** [comment]
Hello, you don't need to-do step 9 just copy the API key and when you run the below command paste it into the terminal when it asks for it.

`python3 setup.py`
