### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by pappabetalar** [Dannyman3819/Automatic-Youtube-Downloader#51]
Hi

When i add a new show to AYD Plex shows the wrong title and i can't figure out what's wrong.
It has worked great in the past to add new shows.
I use the setup.py guide and add title and channel_id then i run main.py again.

![1](https://user-images.githubusercontent.com/11709536/74140141-d1ab7680-4bf4-11ea-8cfa-5d8774c3bf4e.png)
Plex shows the patch to the folder instead of displaying the channel name.

![2](https://user-images.githubusercontent.com/11709536/74140297-1f27e380-4bf5-11ea-93fe-4b2f4d301010.png)
I have edited my library settings, the library is set as "TV shows"

![3](https://user-images.githubusercontent.com/11709536/74140590-9eb5b280-4bf5-11ea-9441-73af610d2d29.png)

I have also edited my agents.

My config is pretty standard.

API_KEY=my_api_key
SCHEDULING_MODE=DELAY
SCHEDULING_MODE_VALUE=30
NUM_VIDEOS=15
DESTINATION_FOLDER=/media/disk6/youtubedl/
DESTINATION_FORMAT=%NAME [Youtube-$CHANNEL_ID]
FILE_FORMAT=%TITLE - [%VIDEO_ID]
VIDEO_FORMAT=4320p

What am i doing wrong?
Running the latest version of AYD, YouTube-Agent.bundle and Absolute-Series-Scanner

**Comment by Silvenga** [comment]
Same issue, might be related to #47.

**Comment by pappabetalar** [comment]
Thank you for your help, much appreciated.
Problem with the agent now.
https://github.com/ZeroQI/YouTube-Agent.bundle/issues/36
